# Generated by Django 2.0.2 on 2018-03-06 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='DEFAULT VALUE', upload_to='images'),
        ),
    ]
